var QUESTIONS = [
  // SELF & GROWTH
  "What's a habit that's quietly improved your life the most?",
  "When do you feel most confident in your own skin?",
  "What's something you've learned about yourself in the past year?",
  "When's a time you surprised yourself in a good way?",
  "What helps you reset when life feels messy?",
  "What's a belief you hold now that your younger self wouldn't understand?",
  "What makes you feel grounded when everything's moving fast?",
  "What's one value you try to live by, even when it's inconvenient?",
  "What's a compliment you still remember years later?",
  "When do you feel most at peace with where you are in life?",
  "What's something you've learned to enjoy that used to feel like a chore?",
  "What personal standard do you hold yourself to, even when nobody's watching?",
  "What's something you've stopped chasing, and why?",
  "What helps you stay kind when you're under pressure?",
  "What's a moment that reminded you you're more resilient than you thought?",
  "What's something you've handled this year that the old you might've avoided?",
  "When do you feel most capable and in control?",
  "What's a daily habit that quietly improves your life?",
  "What's a challenge that made you tougher in a good way?",
  "What helps you stay motivated?",
  "What's a personal win you rarely talk about?",
  "When have you felt proud of handling something maturely?",
  "What's one decision that's aged really well?",
  "What's something you'd tell your younger self about handling pressure?",
  "What's a goal you're quietly working toward right now?",
  "Who reminds you what really matters when you forget?",
  "What helps you bounce back after a setback?",
  "What's a value you've had to defend at least once?",
  "When do you feel the strongest sense of purpose?",
  "When do you find it hardest to slow down?",
  "When do you notice yourself genuinely relaxing?",
  "What helps you reset after a tough day?",
  "When do you feel most focused and alive?",
  "When do you feel most comfortable being completely honest?",
  "What personal habit would you never give up, even if you could?",
  "When do you feel most connected to your purpose?",
  "What's a recent decision that quietly changed your direction?",
  "What helps you stay hopeful when things feel uncertain?",
  "What does 'balance' look like for you right now?",
  "Who brings out the best version of you, and why?",
  "What personal rule or boundary has made your life better?",
  "What's a trait you've grown to appreciate in yourself over time?",
  "What's something you've learned to appreciate that you once took for granted?",
  "When have you felt most grateful for your past mistakes?",
  "What helps you know you're on the right path?",
  "What's a recent challenge that taught you something unexpected about yourself?",
  "What's a personal value that never seems to change?",
  "When do you notice yourself feeling proud?",
  "What's a choice you've made that gave you long-term peace?",
  "What reminds you that you're still growing?",
  "What's something you've done recently that you're proud of?",
  "What's one thing that instantly puts you in a good mood?",
  "What's something you've learned about yourself this year?",
  "What's something that used to scare you but doesn't anymore?",
  "What's one thing that makes you feel grounded?",
  "What's something that makes you feel creative?",
  "What's a risk you'd like to take this year?",
  "What's one thing that helps you feel confident?",
  "What's a personal rule you try to follow?",
  "What's something that helps you stay focused?",
  "What's something that gives you energy?",
  "What's one thing you've recently let go of?",
  "What's a moment that taught you something important?",
  "What's one thing you'd like to do more often?",
  "What's something you're curious to learn next?",
  "What's one thing you're grateful to your past self for?",
  "What's a challenge that taught you resilience?",
  "What's something you enjoy learning about lately?",
  "What's one thing you're trying to worry less about?",
  "What's a decision you're glad you made?",
  "What's something you've done that took courage?",
  "What's something you do differently than most people?",
  "What's something you've recently rediscovered?",
  "What's something you wish you'd learned in school?",
  "What's something you associate with joy?",
  "What's something that feels timeless to you?",
  "What's a habit you'd like to build?",
  "What's a moment you felt completely present?",
  "What's something that makes you feel hopeful?",
  "What's one of your favorite quotes or sayings?",
  "What's something you love to do that others might find unusual?",
  "What's a creative outlet you enjoy?",
  "What's something you've done that took patience?",
  "What's one of your earliest happy memories?",
  "What's something that's currently bringing you peace?",
  "What's one thing you're glad you took a chance on?",
  "What's a way you like to celebrate small wins?",
  "What's a comfort you'd never give up?",
  "What's something you're thankful for in this season of life?",

  // EVERYDAY OBSERVATIONS
  "Why do good ideas always seem to show up in the shower?",
  "What's something that instantly makes a place feel welcoming?",
  "What do you think makes small talk actually enjoyable?",
  "Why do we find it so hard to do nothing?",
  "What's a simple ritual that makes your day feel complete?",
  "What makes a stranger instantly feel trustworthy?",
  "Why do you think people love rewatching old shows?",
  "What's a tiny detail that can completely change your mood?",
  "When does time seem to move the slowest for you?",
  "What's something most people rush that you think should be done slowly?",
  "Why does music make ordinary tasks more enjoyable?",
  "What makes public spaces feel comfortable to be in?",
  "When do you notice people being their most authentic selves?",
  "Why does waiting feel harder now than it used to?",
  "What makes a meal taste better when shared?",
  "Why do people remember some conversations for years?",
  "Why do we find it easier to start projects than finish them?",
  "What makes a quiet moment satisfying instead of awkward?",
  "Why do compliments sometimes feel harder to accept than criticism?",
  "What makes someone's presence calming?",
  "Why does time seem to speed up as we get older?",
  "What makes certain spaces feel instantly familiar?",
  "What small moment makes you think, 'life's pretty good'?",
  "What's something people overcomplicate that should be simple?",
  "Why are we so drawn to routines even when we crave change?",
  "What's a sound that instantly changes your mood?",
  "What's an underrated joy in everyday life?",
  "Why do unfinished conversations stick in our minds?",
  "When do you notice people being most generous?",
  "What makes an apology feel genuine?",
  "When does time seem to disappear for you?",
  "When does a place start to feel like home?",
  "Why do familiar routines feel comforting?",
  "What makes waiting in line more bearable?",
  "What small kindness do you notice most in daily life?",
  "Why do people sometimes open up more at night?",
  "What turns an average weekend into a great one?",
  "What tiny decision in your routine matters more than people think?",
  "What turns an ordinary day into a good one for you?",
  "When does technology actually make life feel simpler?",
  "What makes shared silences comfortable?",
  "What makes you instantly trust someone new?",
  "Why do shared meals create stronger connections?",
  "What makes an apology feel sincere?",
  "What makes ordinary moments memorable?",
  "What makes waiting feel worthwhile?",
  "Why do conversations sometimes feel easier with strangers?",
  "What do you enjoy most about being on your own?",
  "What's your favourite way to spend a slow morning?",
  "What's a small act of kindness that stuck with you?",
  "What's your favourite thing about where you live?",
  "What's a moment from this week that made you smile?",
  "What's your favourite comfort activity?",
  "What's a simple routine that brings you joy?",
  "What's your favourite way to start your morning?",
  "What's a book or show you keep recommending?",
  "What's your favourite way to treat yourself?",
  "What's a place you feel most like yourself?",

  // HYPOTHETICALS & IMAGINATION
  "If you could instantly learn a language, which one and why?",
  "If your day had a soundtrack, what would today's song be?",
  "If you could relive one meal exactly as it was, which would you choose?",
  "If you could add one hour to every day, how would you spend it?",
  "If you could have coffee with your ten-year-older self, what would you talk about?",
  "If you could teleport anywhere right now for a walk, where would you go?",
  "If you could press pause on one part of your life, what would it be?",
  "If you could teach everyone one mindset skill, what would it be?",
  "If you could borrow one trait from a friend for a week, what would it be?",
  "If you could live one year on repeat, which would you choose?",
  "If you could redesign one part of daily life, what would you improve?",
  "If you could remove one daily frustration for everyone, what would it be?",
  "If you could instantly master any skill, what would you choose and why?",
  "If you could have dinner with your childhood self, what would you talk about?",
  "If you could spend a day in someone else's shoes, whose would they be?",
  "If you could hear one honest thought from everyone for a day, would you want to?",
  "If your future self could give you a five-word pep talk, what might it say?",
  "If you could experience one historical event firsthand, which would you choose?",
  "If you could gift your younger self a mindset, what would it be?",
  "If you could take a week off anywhere with zero planning, where would you go?",
  "If you could guarantee one quality in yourself for the next decade, what would it be?",
  "If you could make one everyday task instantly effortless, which would it be?",
  "If you could bring back one tradition that's faded, what would it be?",
  "If tomorrow started with one guaranteed success, what would you choose it to be?",
  "If you could learn a skill just by observing it once, what would you watch?",
  "If you could swap one daily task for a fun one, what would you trade?",
  "If you could rewrite one small rule of modern life, what would you change?",
  "If you could guarantee one universal skill for everyone, what would it be?",
  "If you could step into any photograph from your past, which moment would you visit?",
  "If you could wake up anywhere tomorrow with everything you need, where would it be?",
  "If you could have a short chat with your future self, what would you ask?",
  "If you could erase one pointless annoyance from modern life, what would go?",
  "If you could choose one rule everyone followed for a week, what would it be?",
  "If you could slow one part of life down, what would it be?",
  "If you could instantly understand any subject, which would you dive into?",
  "If you could design a holiday based on rest, what would it involve?",
  "If you could bring back something small from childhood, what would it be?",
  "If you could spend one extra hour each day any way you like, how would you use it?",
  "If you could step into any movie for a day, which story would you live in?",
  "If you could grant yourself one new daily habit overnight, what would it be?",
  "If tomorrow you could add one talent to your skillset, what would it be?",
  "If you could replace one public nuisance with something good, what would you choose?",
  "If you could relive one weekend exactly as it was, which would it be?",
  "If you could experience your favourite moment again, would you change anything?",
  "If you could guarantee one positive trait in everyone, what would it be?",
  "If you could see one year into the future, what would you look for?",
  "What's a place you'd love to return to someday?",
  "What's a meal that reminds you of home?",
  "What's a tradition you'd like to start?",

  // OPINION & REASONING
  "What's something people underestimate the importance of?",
  "Do you think we appreciate quiet enough in daily life?",
  "What helps build real trust between people?",
  "What makes feedback actually helpful instead of discouraging?",
  "What's one thing we should celebrate more often?",
  "Do you think creativity comes more from structure or freedom?",
  "What makes a promise meaningful to you?",
  "How do you tell the difference between persistence and stubbornness?",
  "What makes generosity genuine?",
  "When does honesty require sensitivity?",
  "What's the best way to encourage someone without giving advice?",
  "How can humour change the tone of a tough situation?",
  "What makes progress satisfying even when it's slow?",
  "What makes sincerity stand out in a conversation?",
  "How can disagreement be healthy?",
  "What makes consistency underrated?",
  "How do you define a 'good' risk?",
  "What makes teamwork feel effortless?",
  "How do you know when advice is worth taking?",
  "What keeps curiosity alive as we get older?",
  "How can confidence stay humble?",
  "What makes a group feel united?",
  "How do you define 'doing your best'?",
  "How do you recognise real progress in yourself?",
  "What makes someone easy to forgive?",
  "How do you decide what's worth worrying about?",
  "What makes a place — or group — feel psychologically safe?",
  "How can routine protect creativity instead of limiting it?",
  "What's something worth learning slowly?",
  "What's one thing modern life undervalues?",
  "What do you think helps someone stay humble while succeeding?",
  "Does curiosity require courage?",
  "How does gratitude change the tone of a group?",
  "What separates good advice from great advice?",
  "How do you tell when it's time to move on from something?",
  "What makes something truly worth your time?",
  "What makes a leader someone people want to follow?",
  "What makes honesty easier to hear?",
  "How can small acts of respect change a group's energy?",
  "How do you balance confidence with humility?",
  "What turns hard work into satisfaction instead of stress?",
  "How do you choose what deserves your energy?",
  "What makes kindness powerful even in small doses?",
  "How does empathy show up in leadership?",
  "What makes respect last?",
  "How do you define 'a good conversation'?",
  "What makes authenticity magnetic?",
  "How does gratitude change how we see problems?",
  "How do you balance ambition with contentment?",
  "What helps you maintain perspective when life feels intense?",
  "What makes generosity meaningful?",
  "What makes someone trustworthy beyond words?",
  "How do you recognise when to step back?",
  "What makes encouragement believable?",
  "How do you decide which battles are worth fighting?",
  "What makes you feel fulfilled?",

  // STORY PROMPTS
  "Tell us about a time you had to improvise on the spot.",
  "Share a moment when a stranger helped you unexpectedly.",
  "Describe a time you pushed through even though you didn't feel ready.",
  "Tell us about a time you learned something from a mistake.",
  "Describe a small risk you took that changed your perspective.",
  "Tell us about a time you reconnected with someone after years apart.",
  "Share a time you felt proud of someone else more than yourself.",
  "Tell us about a time you helped someone without expecting anything back.",
  "Share a memory that started as a disaster but turned out great.",
  "Describe a time you got completely lost but ended up somewhere better.",
  "Talk about a lesson you learned the hard way but are glad you did.",
  "Tell us about a goal you achieved after nearly giving up.",
  "Describe a time you stood up for something important to you.",
  "Share a time you laughed at exactly the wrong moment.",
  "Tell us about a time you took a leap before feeling ready.",
  "Share a moment when someone completely changed your mood.",
  "Describe a time you realised you'd underestimated yourself.",
  "Talk about an unexpected lesson you learned from a failure.",
  "Tell us about a time you noticed growth only in hindsight.",
  "Describe a small victory that meant more than anyone realised.",
  "Share a moment when listening changed the outcome.",
  "Tell us about a time you did the right thing even when it cost you.",
  "Describe a situation where patience completely changed the outcome.",
  "Share a time you helped solve a problem in an unexpected way.",
  "Talk about a moment you realised you'd been too hard on yourself.",
  "Tell us about a time you made a quick decision that paid off.",
  "Describe a moment when you genuinely felt proud of your effort, not the result.",
  "Share a time someone believed in you before you did.",
  "Tell us about a time you took a small risk that mattered.",
  "Describe a time you surprised yourself with your own courage.",
  "Share a memory of something simple that turned out meaningful.",
  "Talk about a time you chose rest over pushing through.",
  "Tell us about a person who gave you unexpected encouragement.",
  "Describe a time you said 'yes' before you felt ready.",
  "Tell us about a situation where humour helped.",
  "Share a moment that still makes you smile.",
  "Describe a time when perspective changed everything.",
  "What's a story from your life you love telling?",
  "What's a story from your childhood that still makes you smile?",

  // SELF & GROWTH
  "What is something small that has made your life easier recently?",
  "When do you feel most like yourself?",
  "What is one thing you have become more patient with?",
  "What is something you are learning to accept about yourself?",
  "What is a simple thing that helps you feel calm?",
  "What is something you are better at now than you used to be?",
  "What is one thing you wish you gave yourself more credit for?",
  "What is a recent moment where you felt proud of yourself?",
  "What is something you are trying to make more space for in your life?",
  "What is a habit that makes you feel more prepared for the day?",
  "What is one thing that helps you feel settled after a busy week?",
  "What is something you have learned from being uncomfortable?",
  "What is a small sign that you are doing better than you think?",
  "What is one thing you are slowly getting better at?",
  "What is something that helps you feel more in control?",
  "What is a lesson you keep relearning?",
  "What is something you used to rush but now take your time with?",
  "What is one thing that makes you feel stronger mentally?",
  "What is something you have changed your mind about?",
  "What is a quiet goal you have for yourself?",
  "What is something you are trying not to overthink anymore?",
  "What is one thing that helps you get through a difficult day?",
  "What is something you now value more than you used to?",
  "What is a personal habit that says a lot about you?",
  "What is something you are proud of, even if it seems small?",
  "What is one thing you want to do with more confidence?",
  "What is a simple boundary that has helped you?",
  "What is something you have learned from saying no?",
  "What is something that reminds you to slow down?",
  "What is one thing that makes you feel capable?",
  "What is something you are still figuring out?",
  "What is a personal quality you are glad you have?",
  "What is something you wish you worried less about?",
  "What is a recent moment where you felt grateful?",
  "What is one thing that has helped you grow quietly?",
  "What is something you do when you need to feel grounded?",
  "What is something that has become easier with time?",
  "What is one thing you are learning to trust about yourself?",
  "What is something you want to become more consistent with?",
  "What is one thing that makes you feel refreshed?",
  "What is something that helped you during a stressful time?",
  "What is a simple choice that improved your life?",
  "What is something you are proud of handling calmly?",
  "What is one thing you have learned from your past self?",
  "What is something you want to bring more of into your life?",
  "What is a small win you had this week?",
  "What is something that helps you feel clear-headed?",
  "What is a part of your life that feels better than it used to?",
  "What is something you are learning to enjoy more slowly?",
  "What is one thing you hope future you will thank you for?",

  // EVERYDAY OBSERVATIONS & SIMPLE JOYS
  "What is something ordinary that always makes you smile?",
  "What makes a home feel warm and lived-in?",
  "What is a tiny detail that makes a café or restaurant feel special?",
  "What is your favourite kind of weather, and why?",
  "What is something simple that makes a day feel better?",
  "What is a sound you find comforting?",
  "What is a smell that brings back a memory?",
  "What is a small thing people do that makes you feel welcome?",
  "What makes a walk more enjoyable?",
  "What is something you notice that other people often miss?",
  "What is a simple pleasure you think is underrated?",
  "What makes a conversation feel easy?",
  "What is something you love about slow mornings?",
  "What makes a room feel relaxing?",
  "What is a small thing that can change your mood quickly?",
  "What is something about daily life that you find funny?",
  "What makes waiting less annoying?",
  "What is a routine you secretly enjoy?",
  "What is something people do in public that restores your faith in humanity?",
  "What is a tiny luxury you appreciate?",
  "What makes a neighbourhood feel friendly?",
  "What is your favourite kind of weekend plan?",
  "What is something you enjoy doing alone?",
  "What is a place where you feel comfortable doing nothing?",
  "What makes a shared meal feel meaningful?",
  "What is a small habit that makes someone pleasant to be around?",
  "What is something that makes public transport more bearable?",
  "What is a small moment that feels peaceful to you?",
  "What is something that makes you feel nostalgic?",
  "What is something you enjoy more when you do it slowly?",
  "What makes a gathering feel relaxed instead of awkward?",
  "What is something you like about your daily routine?",
  "What is a small kindness you appreciate from strangers?",
  "What is something that makes you feel at home in a new place?",
  "What is a comfort food that always works for you?",
  "What makes a day feel productive but not stressful?",
  "What is something you like to notice when you travel?",
  "What is something about nature that always catches your attention?",
  "What makes a familiar place feel special?",
  "What is a small thing that makes you feel cared for?",
  "What is an everyday object you appreciate more than most people do?",
  "What is something you enjoy about quiet moments?",
  "What is your favourite way to end the day?",
  "What makes a simple plan feel fun?",
  "What is a small thing that makes you feel organised?",
  "What is something that makes you feel connected to your community?",
  "What is a daily moment you wish lasted longer?",
  "What is something ordinary that feels beautiful to you?",
  "What makes a place feel safe?",
  "What is a tiny thing that improves your mood every time?",

  // PEOPLE, CONNECTION & RELATIONSHIPS
  "What is a quality you appreciate in a good friend?",
  "What makes someone easy to talk to?",
  "What is something small that makes you feel supported?",
  "What is a friendship lesson you have learned over time?",
  "What makes someone a good listener?",
  "What is something you appreciate more in people as you get older?",
  "What makes you feel comfortable around someone new?",
  "What is a simple way people show they care?",
  "What is something a friend has taught you without realising it?",
  "What makes a group feel welcoming?",
  "What is a kind gesture you still remember?",
  "What makes a conversation feel meaningful?",
  "What is something you admire in other people?",
  "What helps you feel understood?",
  "What is a green flag in a friendship?",
  "What makes someone's energy calming?",
  "What is something you value in your closest relationships?",
  "What is a small thing that can make someone feel included?",
  "What is something you have learned from meeting new people?",
  "What makes someone memorable after one conversation?",
  "What is a good way to make someone feel welcome?",
  "What is something you appreciate when someone disagrees respectfully?",
  "What makes a compliment feel genuine?",
  "What is a quality you wish more people noticed in others?",
  "What makes you trust someone over time?",
  "What is something a stranger said that stayed with you?",
  "What is a simple way to brighten someone's day?",
  "What makes someone fun to be around?",
  "What helps you open up to people?",
  "What is something you have learned from a difficult conversation?",
  "What makes a person feel safe to be honest with?",
  "What is something you appreciate about your family or chosen family?",
  "What is a friendship you are grateful for?",
  "What is a small sign someone is paying attention?",
  "What is something you think strengthens connection between people?",
  "What is a moment when you felt genuinely seen?",
  "What is a simple way to show respect?",
  "What is a quality that makes someone a good teammate?",
  "What makes people feel comfortable laughing together?",
  "What is something you appreciate about people who are different from you?",
  "What makes an apology feel real?",
  "What is one thing you think people should say more often?",
  "What is something you learned from someone older than you?",
  "What is something you learned from someone younger than you?",
  "What makes a shared experience unforgettable?",
  "What is a small thing that builds trust?",
  "What makes a community feel alive?",
  "What is something you admire in someone close to you?",
  "What kind of person brings out the best in you?",

  // LIGHT HYPOTHETICALS & IMAGINATION
  "If you could wake up with one new skill tomorrow, what would it be?",
  "If you could spend a day in any city, where would you go?",
  "If you could bring back one childhood activity, what would it be?",
  "If your life this week had a title, what would it be?",
  "If you could make one chore disappear forever, which one would you choose?",
  "If you could have unlimited time for one hobby, what would it be?",
  "If you could give everyone one extra hour today, how should they use it?",
  "If you could instantly become better at one everyday skill, what would it be?",
  "If you could design the perfect Sunday, what would it include?",
  "If you could have dinner anywhere in the world tonight, where would you go?",
  "If you could swap lives with someone for one day, who would you choose?",
  "If you could relive one ordinary day, which day would it be?",
  "If you could turn one memory into a short film, what would it show?",
  "If you could bring one fictional place to life, where would it be?",
  "If you could make one public rule that everyone followed, what would it be?",
  "If you could choose the soundtrack for your morning, what song would play?",
  "If you could instantly understand one topic, what would you choose?",
  "If you could invite three people to a relaxed dinner, who would you invite?",
  "If you could make one part of adult life easier, what would it be?",
  "If you could live near any natural landscape, what would you choose?",
  "If you could receive one helpful message from your future self, what would it say?",
  "If you could go back and thank one person, who would it be?",
  "If you could create a new holiday, what would it celebrate?",
  "If you could be known for one quality, what would you want it to be?",
  "If you could make one everyday item more beautiful, what would you redesign?",
  "If you could spend a week without one modern technology, what would you choose?",
  "If you could learn one dance, sport, or movement skill, what would it be?",
  "If you could revisit one place from your past, where would you go?",
  "If you could make one thing free for everyone, what would it be?",
  "If you could choose one thing to be naturally good at, what would it be?",
  "If you could add one tradition to your year, what would it be?",
  "If you could have a conversation with your teenage self, what would you say first?",
  "If you could choose one view to look at every morning, what would it be?",
  "If you could create your ideal neighbourhood, what would it include?",
  "If you could make one simple thing last longer, what would it be?",
  "If you could spend a day learning from an expert, what would you learn?",
  "If you could turn one hobby into a mini adventure, what would you do?",
  "If you could bring one old trend back, what would it be?",
  "If you could remove one source of stress from daily life, what would you remove?",
  "If you could make one boring task enjoyable, what would it be?",
  "If you could choose your perfect morning routine, what would it look like?",
  "If you could receive a surprise gift today, what would you hope it is?",
  "If you could visit any place just for lunch, where would you go?",
  "If you could spend one day as a beginner again, what would you try?",
  "If you could make one room in your home perfect, which room would it be?",
  "If you could only keep three apps on your phone, which would they be?",
  "If you could make one skill easier for everyone to learn, what would it be?",
  "If you could choose a theme for the next month of your life, what would it be?",
  "If you could turn one small dream into reality this year, what would it be?",
  "If you could give everyone one tiny daily joy, what would it be?",

  // STORY PROMPTS & PERSONAL REFLECTIONS
  "Tell us about a time you changed your mind about something.",
  "Tell us about a small moment that made your day better.",
  "Share a time you learned something from someone unexpected.",
  "Tell us about a moment when you felt brave in a quiet way.",
  "Share a time you tried something new and surprised yourself.",
  "Tell us about a time a small plan turned into a great memory.",
  "Share a time you felt welcomed by a group or person.",
  "Tell us about a moment when you felt proud of your progress.",
  "Share a time when a simple conversation stayed with you.",
  "Tell us about a time you had to adjust your expectations.",
  "Share a memory of a place that felt special to you.",
  "Tell us about a time you laughed harder than expected.",
  "Share a time when someone made something easier for you.",
  "Tell us about a moment when you realised you had grown.",
  "Share a time you felt nervous but did it anyway.",
  "Tell us about a time you enjoyed something more than you expected.",
  "Share a time you received advice that actually helped.",
  "Tell us about a time you had to be patient.",
  "Share a time you made a small decision that mattered.",
  "Tell us about a time you felt grateful for good timing.",
  "Share a memory connected to food.",
  "Tell us about a time you felt completely present.",
  "Share a time you helped someone in a small way.",
  "Tell us about a time someone encouraged you.",
  "Share a moment when you felt calm after feeling stressed.",
  "Tell us about a time you found joy in something simple.",
  "Share a time when you realised you were stronger than you thought.",
  "Tell us about a time you learned by watching someone else.",
  "Share a time when something didn't go to plan but still worked out.",
  "Tell us about a time you felt connected to a place.",
  "Share a time you had to speak up.",
  "Tell us about a moment that reminded you to slow down.",
  "Share a time you made someone else smile.",
  "Tell us about a time you felt proud of showing up.",
  "Share a time you discovered something new about yourself.",
  "Tell us about a time you received kindness from a stranger.",
  "Share a time when you had to trust the process.",
  "Tell us about a time you took care of yourself well.",
  "Share a moment when you felt lucky.",
  "Tell us about a time you learned something from failure.",
  "Share a time when you felt at home somewhere unexpected.",
  "Tell us about a time you had to make the best of a situation.",
  "Share a memory of a simple day that still makes you happy.",
  "Tell us about a time you realised something important about friendship.",
  "Share a time you enjoyed being a beginner.",
  "Tell us about a time you did something even though it felt awkward.",
  "Share a time when someone's honesty helped you.",
  "Tell us about a moment when you felt quietly confident.",
  "Share a time you appreciated something only after it was gone.",
  "Tell us about a time you felt proud of how far you've come.",
];
