var QUESTIONS = [
  // SELF & GROWTH
  "What's a habit that's quietly improved your life the most?",
  "When do you feel most confident in your own skin?",
  "What's something you've learned about yourself in the past year?",
  "When's a time you surprised yourself in a good way?",
  "What helps you reset when life feels messy?",
  "What's a belief you hold now that your younger self wouldn't understand?",
  "What makes you feel grounded when everything's moving fast?",
  "What's one value you try to live by, even when it's inconvenient?",
  "What's a compliment you still remember years later?",
  "When do you feel most at peace with where you are in life?",
  "What's something you've learned to enjoy that used to feel like a chore?",
  "What personal standard do you hold yourself to, even when nobody's watching?",
  "What's something you've stopped chasing, and why?",
  "What helps you stay kind when you're under pressure?",
  "What's a moment that reminded you you're more resilient than you thought?",
  "What's something you've handled this year that the old you might've avoided?",
  "When do you feel most capable and in control?",
  "What's a daily habit that quietly improves your life?",
  "What's a challenge that made you tougher in a good way?",
  "What helps you stay motivated?",
  "What's a personal win you rarely talk about?",
  "When have you felt proud of handling something maturely?",
  "What's one decision that's aged really well?",
  "What's something you'd tell your younger self about handling pressure?",
  "What's a goal you're quietly working toward right now?",
  "Who reminds you what really matters when you forget?",
  "What helps you bounce back after a setback?",
  "What's a value you've had to defend at least once?",
  "When do you feel the strongest sense of purpose?",
  "When do you find it hardest to slow down?",
  "When do you notice yourself genuinely relaxing?",
  "What helps you reset after a tough day?",
  "When do you feel most focused and alive?",
  "When do you feel most comfortable being completely honest?",
  "What personal habit would you never give up, even if you could?",
  "When do you feel most connected to your purpose?",
  "What's a recent decision that quietly changed your direction?",
  "What helps you stay hopeful when things feel uncertain?",
  "What does 'balance' look like for you right now?",
  "Who brings out the best version of you, and why?",
  "What personal rule or boundary has made your life better?",
  "What's a trait you've grown to appreciate in yourself over time?",
  "What's something you've learned to appreciate that you once took for granted?",
  "When have you felt most grateful for your past mistakes?",
  "What helps you know you're on the right path?",
  "What's a recent challenge that taught you something unexpected about yourself?",
  "What's a personal value that never seems to change?",
  "When do you notice yourself feeling proud?",
  "What's a choice you've made that gave you long-term peace?",
  "What reminds you that you're still growing?",
  "What's something you've done recently that you're proud of?",
  "What's one thing that instantly puts you in a good mood?",
  "What's something you've learned about yourself this year?",
  "What's something that used to scare you but doesn't anymore?",
  "What's one thing that makes you feel grounded?",
  "What's something that makes you feel creative?",
  "What's a risk you'd like to take this year?",
  "What's one thing that helps you feel confident?",
  "What's a personal rule you try to follow?",
  "What's something that helps you stay focused?",
  "What's something that gives you energy?",
  "What's one thing you've recently let go of?",
  "What's a moment that taught you something important?",
  "What's one thing you'd like to do more often?",
  "What's something you're curious to learn next?",
  "What's one thing you're grateful to your past self for?",
  "What's a challenge that taught you resilience?",
  "What's something you enjoy learning about lately?",
  "What's one thing you're trying to worry less about?",
  "What's a decision you're glad you made?",
  "What's something you've done that took courage?",
  "What's something you do differently than most people?",
  "What's something you've recently rediscovered?",
  "What's something you wish you'd learned in school?",
  "What's something you associate with joy?",
  "What's something that feels timeless to you?",
  "What's a habit you'd like to build?",
  "What's a moment you felt completely present?",
  "What's something that makes you feel hopeful?",
  "What's one of your favorite quotes or sayings?",
  "What's something you love to do that others might find unusual?",
  "What's a creative outlet you enjoy?",
  "What's something you've done that took patience?",
  "What's one of your earliest happy memories?",
  "What's something that's currently bringing you peace?",
  "What's one thing you're glad you took a chance on?",
  "What's a way you like to celebrate small wins?",
  "What's a comfort you'd never give up?",
  "What's something you're thankful for in this season of life?",

  // EVERYDAY OBSERVATIONS
  "Why do good ideas always seem to show up in the shower?",
  "What's something that instantly makes a place feel welcoming?",
  "What do you think makes small talk actually enjoyable?",
  "Why do we find it so hard to do nothing?",
  "What's a simple ritual that makes your day feel complete?",
  "What makes a stranger instantly feel trustworthy?",
  "Why do you think people love rewatching old shows?",
  "What's a tiny detail that can completely change your mood?",
  "When does time seem to move the slowest for you?",
  "What's something most people rush that you think should be done slowly?",
  "Why does music make ordinary tasks more enjoyable?",
  "What makes public spaces feel comfortable to be in?",
  "When do you notice people being their most authentic selves?",
  "Why does waiting feel harder now than it used to?",
  "What makes a meal taste better when shared?",
  "Why do people remember some conversations for years?",
  "Why do we find it easier to start projects than finish them?",
  "What makes a quiet moment satisfying instead of awkward?",
  "Why do compliments sometimes feel harder to accept than criticism?",
  "What makes someone's presence calming?",
  "Why does time seem to speed up as we get older?",
  "What makes certain spaces feel instantly familiar?",
  "What small moment makes you think, 'life's pretty good'?",
  "What's something people overcomplicate that should be simple?",
  "Why are we so drawn to routines even when we crave change?",
  "What's a sound that instantly changes your mood?",
  "What's an underrated joy in everyday life?",
  "Why do unfinished conversations stick in our minds?",
  "When do you notice people being most generous?",
  "What makes an apology feel genuine?",
  "When does time seem to disappear for you?",
  "When does a place start to feel like home?",
  "Why do familiar routines feel comforting?",
  "What makes waiting in line more bearable?",
  "What small kindness do you notice most in daily life?",
  "Why do people sometimes open up more at night?",
  "What turns an average weekend into a great one?",
  "What tiny decision in your routine matters more than people think?",
  "What turns an ordinary day into a good one for you?",
  "When does technology actually make life feel simpler?",
  "What makes shared silences comfortable?",
  "What makes you instantly trust someone new?",
  "Why do shared meals create stronger connections?",
  "What makes an apology feel sincere?",
  "What makes ordinary moments memorable?",
  "What makes waiting feel worthwhile?",
  "Why do conversations sometimes feel easier with strangers?",
  "What do you enjoy most about being on your own?",
  "What's your favourite way to spend a slow morning?",
  "What's a small act of kindness that stuck with you?",
  "What's your favourite thing about where you live?",
  "What's a moment from this week that made you smile?",
  "What's your favourite comfort activity?",
  "What's a simple routine that brings you joy?",
  "What's your favourite way to start your morning?",
  "What's a book or show you keep recommending?",
  "What's your favourite way to treat yourself?",
  "What's a place you feel most like yourself?",

  // HYPOTHETICALS & IMAGINATION
  "If you could instantly learn a language, which one and why?",
  "If your day had a soundtrack, what would today's song be?",
  "If you could relive one meal exactly as it was, which would you choose?",
  "If you could add one hour to every day, how would you spend it?",
  "If you could have coffee with your ten-year-older self, what would you talk about?",
  "If you could teleport anywhere right now for a walk, where would you go?",
  "If you could press pause on one part of your life, what would it be?",
  "If you could teach everyone one mindset skill, what would it be?",
  "If you could borrow one trait from a friend for a week, what would it be?",
  "If you could live one year on repeat, which would you choose?",
  "If you could redesign one part of daily life, what would you improve?",
  "If you could remove one daily frustration for everyone, what would it be?",
  "If you could instantly master any skill, what would you choose and why?",
  "If you could have dinner with your childhood self, what would you talk about?",
  "If you could spend a day in someone else's shoes, whose would they be?",
  "If you could hear one honest thought from everyone for a day, would you want to?",
  "If your future self could give you a five-word pep talk, what might it say?",
  "If you could experience one historical event firsthand, which would you choose?",
  "If you could gift your younger self a mindset, what would it be?",
  "If you could take a week off anywhere with zero planning, where would you go?",
  "If you could guarantee one quality in yourself for the next decade, what would it be?",
  "If you could make one everyday task instantly effortless, which would it be?",
  "If you could bring back one tradition that's faded, what would it be?",
  "If tomorrow started with one guaranteed success, what would you choose it to be?",
  "If you could learn a skill just by observing it once, what would you watch?",
  "If you could swap one daily task for a fun one, what would you trade?",
  "If you could rewrite one small rule of modern life, what would you change?",
  "If you could guarantee one universal skill for everyone, what would it be?",
  "If you could step into any photograph from your past, which moment would you visit?",
  "If you could wake up anywhere tomorrow with everything you need, where would it be?",
  "If you could have a short chat with your future self, what would you ask?",
  "If you could erase one pointless annoyance from modern life, what would go?",
  "If you could choose one rule everyone followed for a week, what would it be?",
  "If you could slow one part of life down, what would it be?",
  "If you could instantly understand any subject, which would you dive into?",
  "If you could design a holiday based on rest, what would it involve?",
  "If you could bring back something small from childhood, what would it be?",
  "If you could spend one extra hour each day any way you like, how would you use it?",
  "If you could step into any movie for a day, which story would you live in?",
  "If you could grant yourself one new daily habit overnight, what would it be?",
  "If tomorrow you could add one talent to your skillset, what would it be?",
  "If you could replace one public nuisance with something good, what would you choose?",
  "If you could relive one weekend exactly as it was, which would it be?",
  "If you could experience your favourite moment again, would you change anything?",
  "If you could guarantee one positive trait in everyone, what would it be?",
  "If you could see one year into the future, what would you look for?",
  "What's a place you'd love to return to someday?",
  "What's a meal that reminds you of home?",
  "What's a tradition you'd like to start?",

  // OPINION & REASONING
  "What's something people underestimate the importance of?",
  "Do you think we appreciate quiet enough in daily life?",
  "What helps build real trust between people?",
  "What makes feedback actually helpful instead of discouraging?",
  "What's one thing we should celebrate more often?",
  "Do you think creativity comes more from structure or freedom?",
  "What makes a promise meaningful to you?",
  "How do you tell the difference between persistence and stubbornness?",
  "What makes generosity genuine?",
  "When does honesty require sensitivity?",
  "What's the best way to encourage someone without giving advice?",
  "How can humour change the tone of a tough situation?",
  "What makes progress satisfying even when it's slow?",
  "What makes sincerity stand out in a conversation?",
  "How can disagreement be healthy?",
  "What makes consistency underrated?",
  "How do you define a 'good' risk?",
  "What makes teamwork feel effortless?",
  "How do you know when advice is worth taking?",
  "What keeps curiosity alive as we get older?",
  "How can confidence stay humble?",
  "What makes a group feel united?",
  "How do you define 'doing your best'?",
  "How do you recognise real progress in yourself?",
  "What makes someone easy to forgive?",
  "How do you decide what's worth worrying about?",
  "What makes a place — or group — feel psychologically safe?",
  "How can routine protect creativity instead of limiting it?",
  "What's something worth learning slowly?",
  "What's one thing modern life undervalues?",
  "What do you think helps someone stay humble while succeeding?",
  "Does curiosity require courage?",
  "How does gratitude change the tone of a group?",
  "What separates good advice from great advice?",
  "How do you tell when it's time to move on from something?",
  "What makes something truly worth your time?",
  "What makes a leader someone people want to follow?",
  "What makes honesty easier to hear?",
  "How can small acts of respect change a group's energy?",
  "How do you balance confidence with humility?",
  "What turns hard work into satisfaction instead of stress?",
  "How do you choose what deserves your energy?",
  "What makes kindness powerful even in small doses?",
  "How does empathy show up in leadership?",
  "What makes respect last?",
  "How do you define 'a good conversation'?",
  "What makes authenticity magnetic?",
  "How does gratitude change how we see problems?",
  "How do you balance ambition with contentment?",
  "What helps you maintain perspective when life feels intense?",
  "What makes generosity meaningful?",
  "What makes someone trustworthy beyond words?",
  "How do you recognise when to step back?",
  "What makes encouragement believable?",
  "How do you decide which battles are worth fighting?",
  "What makes you feel fulfilled?",

  // STORY PROMPTS
  "Tell us about a time you had to improvise on the spot.",
  "Share a moment when a stranger helped you unexpectedly.",
  "Describe a time you pushed through even though you didn't feel ready.",
  "Tell us about a time you learned something from a mistake.",
  "Describe a small risk you took that changed your perspective.",
  "Tell us about a time you reconnected with someone after years apart.",
  "Share a time you felt proud of someone else more than yourself.",
  "Tell us about a time you helped someone without expecting anything back.",
  "Share a memory that started as a disaster but turned out great.",
  "Describe a time you got completely lost but ended up somewhere better.",
  "Talk about a lesson you learned the hard way but are glad you did.",
  "Tell us about a goal you achieved after nearly giving up.",
  "Describe a time you stood up for something important to you.",
  "Share a time you laughed at exactly the wrong moment.",
  "Tell us about a time you took a leap before feeling ready.",
  "Share a moment when someone completely changed your mood.",
  "Describe a time you realised you'd underestimated yourself.",
  "Talk about an unexpected lesson you learned from a failure.",
  "Tell us about a time you noticed growth only in hindsight.",
  "Describe a small victory that meant more than anyone realised.",
  "Share a moment when listening changed the outcome.",
  "Tell us about a time you did the right thing even when it cost you.",
  "Describe a situation where patience completely changed the outcome.",
  "Share a time you helped solve a problem in an unexpected way.",
  "Talk about a moment you realised you'd been too hard on yourself.",
  "Tell us about a time you made a quick decision that paid off.",
  "Describe a moment when you genuinely felt proud of your effort, not the result.",
  "Share a time someone believed in you before you did.",
  "Tell us about a time you took a small risk that mattered.",
  "Describe a time you surprised yourself with your own courage.",
  "Share a memory of something simple that turned out meaningful.",
  "Talk about a time you chose rest over pushing through.",
  "Tell us about a person who gave you unexpected encouragement.",
  "Describe a time you said 'yes' before you felt ready.",
  "Tell us about a situation where humour helped.",
  "Share a moment that still makes you smile.",
  "Describe a time when perspective changed everything.",
  "What's a story from your life you love telling?",
  "What's a story from your childhood that still makes you smile?"
];
