// data.js — the prompt bank. Batch 2026-09: 282 Table Topics prompts across
// 39 themes. Each prompt has a stable id, a theme, and a style:
//   you      — the speaker shares something about themselves
//   scenario — a creative setup: an "If..." stem to complete, or a speech format
//   big      — a philosophical question about people and life in general
// Prompts ending in "..." are sentence stems and are shown as written.
//
// Selection rules live in screens.jsx (QuestionSelectScreen) and app.jsx
// (pickYoloQuestion). Ids are what the persistent "done" list stores, so
// keep them stable when editing text; add new prompts with new ids.

var PROMPTS = [
  // Beginner's Mind
  { id: "q001", theme: "beginners-mind", type: "you", text: "What's something you were terrible at when you started?" },
  { id: "q002", theme: "beginners-mind", type: "you", text: "Tell us about the last thing you were a complete beginner at." },
  { id: "q003", theme: "beginners-mind", type: "you", text: "Tell us about the first time you tried something you now love." },
  { id: "q004", theme: "beginners-mind", type: "scenario", text: "If I started a new hobby tomorrow..." },
  { id: "q005", theme: "beginners-mind", type: "scenario", text: "If I could be a beginner again at something I love..." },
  { id: "q006", theme: "beginners-mind", type: "scenario", text: "Teach us the first lesson of something you know well." },
  { id: "q007", theme: "beginners-mind", type: "big", text: "Does learning get harder with age?" },
  { id: "q008", theme: "beginners-mind", type: "big", text: "Does being an expert make it harder to keep learning?" },
  // Surprise
  { id: "q009", theme: "surprise", type: "you", text: "What's something that surprised you recently?" },
  { id: "q010", theme: "surprise", type: "you", text: "What's a place that was nothing like you imagined?" },
  { id: "q011", theme: "surprise", type: "scenario", text: "Tell us something about yourself that would surprise this room." },
  { id: "q012", theme: "surprise", type: "big", text: "Do we lose our sense of wonder as we get older?" },
  { id: "q013", theme: "surprise", type: "big", text: "Are surprises better than plans?" },
  // A Ship in Harbor
  { id: "q014", theme: "ship-in-harbor", type: "you", text: "What's the scariest thing you've said yes to?" },
  { id: "q015", theme: "ship-in-harbor", type: "you", text: "Tell us about a risk you're glad you took." },
  { id: "q016", theme: "ship-in-harbor", type: "you", text: "What's something small that still pushes you out of your comfort zone?" },
  { id: "q017", theme: "ship-in-harbor", type: "you", text: "Tell us about a time you surprised yourself by giving something a go." },
  { id: "q018", theme: "ship-in-harbor", type: "scenario", text: "If I said yes to everything for a week..." },
  { id: "q019", theme: "ship-in-harbor", type: "scenario", text: "If I weren't worried about looking silly..." },
  { id: "q020", theme: "ship-in-harbor", type: "scenario", text: "If I had one year to do something bold..." },
  { id: "q021", theme: "ship-in-harbor", type: "scenario", text: "Dare this room to try one thing this week." },
  { id: "q022", theme: "ship-in-harbor", type: "big", text: "Is playing it safe a risk in itself?" },
  { id: "q023", theme: "ship-in-harbor", type: "big", text: "Can you grow without discomfort?" },
  // Bring Your Own Sunshine
  { id: "q024", theme: "bring-your-own-sunshine", type: "you", text: "What's something that reliably lifts your mood?" },
  { id: "q025", theme: "bring-your-own-sunshine", type: "you", text: "Tell us about someone who brightens any room they walk into." },
  { id: "q026", theme: "bring-your-own-sunshine", type: "you", text: "Tell us about a day that turned around unexpectedly." },
  { id: "q027", theme: "bring-your-own-sunshine", type: "scenario", text: "If I could bottle one good mood..." },
  { id: "q028", theme: "bring-your-own-sunshine", type: "scenario", text: "If every day had perfect weather..." },
  { id: "q029", theme: "bring-your-own-sunshine", type: "scenario", text: "If I could give this room one good habit..." },
  { id: "q030", theme: "bring-your-own-sunshine", type: "big", text: "Can being too positive be a bad thing?" },
  // Navigating Transitions
  { id: "q031", theme: "navigating-transitions", type: "you", text: "What's a change you resisted that turned out well?" },
  { id: "q032", theme: "navigating-transitions", type: "you", text: "Tell us about a skill that carried over from one part of your life to another." },
  { id: "q033", theme: "navigating-transitions", type: "scenario", text: "If I could switch careers for a year..." },
  { id: "q034", theme: "navigating-transitions", type: "scenario", text: "Share the advice you'd give someone starting something new tomorrow." },
  { id: "q035", theme: "navigating-transitions", type: "big", text: "Is it harder to start something or to end something?" },
  { id: "q036", theme: "navigating-transitions", type: "big", text: "Does change get easier the more you go through it?" },
  // The Need to Improve
  { id: "q037", theme: "need-to-improve", type: "you", text: "Tell us about a time you improved something just for yourself." },
  { id: "q038", theme: "need-to-improve", type: "you", text: "What's a skill you keep chipping away at?" },
  { id: "q039", theme: "need-to-improve", type: "you", text: "Tell us about the moment you realised you'd got good at something." },
  { id: "q040", theme: "need-to-improve", type: "scenario", text: "If nobody ever saw my work..." },
  { id: "q041", theme: "need-to-improve", type: "scenario", text: "If I could practise one thing for an hour every day..." },
  { id: "q042", theme: "need-to-improve", type: "big", text: "Is it better to be motivated by others or by yourself?" },
  { id: "q043", theme: "need-to-improve", type: "big", text: "Can you ever be finished improving?" },
  // Laughter
  { id: "q044", theme: "laughter", type: "you", text: "What's something serious in your life that humour helps with?" },
  { id: "q045", theme: "laughter", type: "scenario", text: "If nobody took anything too seriously..." },
  { id: "q046", theme: "laughter", type: "scenario", text: "Explain your sense of humour to someone who's never met you." },
  { id: "q047", theme: "laughter", type: "scenario", text: "Tell us about the funniest misunderstanding you've been part of." },
  { id: "q048", theme: "laughter", type: "big", text: "Is there anything we shouldn't joke about?" },
  // Gratitude
  { id: "q049", theme: "gratitude", type: "you", text: "What's something ordinary you're grateful for?" },
  { id: "q050", theme: "gratitude", type: "you", text: "Tell us about someone you've never properly thanked." },
  { id: "q051", theme: "gratitude", type: "you", text: "What's something you took for granted until it was gone?" },
  { id: "q052", theme: "gratitude", type: "you", text: "Tell us about a small thing that went right this week." },
  { id: "q053", theme: "gratitude", type: "scenario", text: "If I noticed one good thing every day for a year..." },
  { id: "q054", theme: "gratitude", type: "scenario", text: "Make the case for saying thank you more often." },
  { id: "q055", theme: "gratitude", type: "scenario", text: "Tell us about an invention you're glad exists." },
  { id: "q056", theme: "gratitude", type: "big", text: "Can you be grateful and still want more?" },
  { id: "q057", theme: "gratitude", type: "big", text: "Does gratitude make people happier, or do happy people feel more grateful?" },
  // Heritage
  { id: "q058", theme: "heritage", type: "you", text: "What's a family tradition you'd like to keep alive?" },
  { id: "q059", theme: "heritage", type: "you", text: "Tell us about a dish that connects you to where you come from." },
  { id: "q060", theme: "heritage", type: "you", text: "What's a place that feels like it belongs to you?" },
  { id: "q061", theme: "heritage", type: "scenario", text: "Give us a tour of the landscape you grew up in." },
  { id: "q062", theme: "heritage", type: "big", text: "Can you belong to a place you weren't born in?" },
  // Curiosity
  { id: "q063", theme: "curiosity", type: "you", text: "What's something you've been curious about lately?" },
  { id: "q064", theme: "curiosity", type: "you", text: "Tell us about a rabbit hole you fell down recently." },
  { id: "q065", theme: "curiosity", type: "you", text: "What's something you've always wondered how it works?" },
  { id: "q066", theme: "curiosity", type: "you", text: "Tell us about a time curiosity led you somewhere new." },
  { id: "q067", theme: "curiosity", type: "scenario", text: "If I could get an honest answer to any question..." },
  { id: "q068", theme: "curiosity", type: "scenario", text: "Teach us the most fascinating thing you learned this year." },
  { id: "q069", theme: "curiosity", type: "big", text: "Can curiosity be taught?" },
  { id: "q070", theme: "curiosity", type: "big", text: "Does the internet make us more curious or less?" },
  // Listening
  { id: "q071", theme: "listening", type: "you", text: "Who's the best listener you know?" },
  { id: "q072", theme: "listening", type: "you", text: "Tell us about a conversation that stuck with you." },
  { id: "q073", theme: "listening", type: "you", text: "What's something you learned just by listening?" },
  { id: "q074", theme: "listening", type: "you", text: "Tell us about a time you realised you weren't really listening." },
  { id: "q075", theme: "listening", type: "scenario", text: "If everyone listened twice as much as they talked..." },
  { id: "q076", theme: "listening", type: "scenario", text: "Give us your best advice for listening well." },
  { id: "q077", theme: "listening", type: "big", text: "Is listening a skill or a habit?" },
  // Together
  { id: "q078", theme: "together", type: "you", text: "What's the best team you've ever been part of?" },
  { id: "q079", theme: "together", type: "you", text: "Tell us about something you could never have done alone." },
  { id: "q080", theme: "together", type: "you", text: "What's a group you feel most at home in?" },
  { id: "q081", theme: "together", type: "you", text: "Tell us about a time a group of strangers came together." },
  { id: "q082", theme: "together", type: "scenario", text: "If I could get any group of people in one room..." },
  { id: "q083", theme: "together", type: "big", text: "Do we achieve more alone or together?" },
  { id: "q084", theme: "together", type: "big", text: "What makes a group of people become a community?" },
  // Small Steps
  { id: "q085", theme: "small-steps", type: "you", text: "What's a small habit that made a big difference for you?" },
  { id: "q086", theme: "small-steps", type: "you", text: "Tell us about a big goal you reached one step at a time." },
  { id: "q087", theme: "small-steps", type: "you", text: "What's the first step you've been putting off?" },
  { id: "q088", theme: "small-steps", type: "scenario", text: "If I did one tiny thing differently every day..." },
  { id: "q089", theme: "small-steps", type: "big", text: "Is it better to start small or aim big?" },
  { id: "q090", theme: "small-steps", type: "big", text: "Do small changes really add up?" },
  // Time
  { id: "q091", theme: "time", type: "you", text: "What's something you always make time for?" },
  { id: "q092", theme: "time", type: "you", text: "Tell us about a day that flew by." },
  { id: "q093", theme: "time", type: "you", text: "What's something you wish you'd started sooner?" },
  { id: "q094", theme: "time", type: "you", text: "Tell us about how you spend your favourite free hour." },
  { id: "q095", theme: "time", type: "scenario", text: "If I had an extra hour every day..." },
  { id: "q096", theme: "time", type: "scenario", text: "If clocks disappeared tomorrow..." },
  { id: "q097", theme: "time", type: "scenario", text: "If I could slow down one moment..." },
  { id: "q098", theme: "time", type: "big", text: "Is being busy the same as being productive?" },
  { id: "q099", theme: "time", type: "big", text: "Does time really go faster as we get older?" },
  // Creativity
  { id: "q100", theme: "creativity", type: "you", text: "What's something you've made that you're proud of?" },
  { id: "q101", theme: "creativity", type: "you", text: "Tell us about where you get your best ideas." },
  { id: "q102", theme: "creativity", type: "you", text: "What's a creative outlet you'd love to try?" },
  { id: "q103", theme: "creativity", type: "you", text: "Tell us about someone whose creativity inspires you." },
  { id: "q104", theme: "creativity", type: "scenario", text: "If I had a whole day to make something..." },
  { id: "q105", theme: "creativity", type: "scenario", text: "If I could master one art form overnight..." },
  { id: "q106", theme: "creativity", type: "scenario", text: "Pitch us an idea you've had but never acted on." },
  { id: "q107", theme: "creativity", type: "big", text: "Is everyone creative?" },
  { id: "q108", theme: "creativity", type: "big", text: "Do limits make us more creative?" },
  // Play
  { id: "q109", theme: "play", type: "you", text: "Tell us about something you do purely for fun." },
  { id: "q110", theme: "play", type: "you", text: "What's a playful habit you've kept as an adult?" },
  { id: "q111", theme: "play", type: "you", text: "Tell us about the last time you completely lost track of time." },
  { id: "q112", theme: "play", type: "scenario", text: "If adults had recess..." },
  { id: "q113", theme: "play", type: "scenario", text: "If every workplace had a playground..." },
  { id: "q114", theme: "play", type: "big", text: "Do adults play enough?" },
  { id: "q115", theme: "play", type: "big", text: "Can work ever feel like play?" },
  // Simplicity
  { id: "q116", theme: "simplicity", type: "you", text: "What's something you've simplified in your life?" },
  { id: "q117", theme: "simplicity", type: "you", text: "Tell us about a simple pleasure you never get tired of." },
  { id: "q118", theme: "simplicity", type: "you", text: "What's something you own that you'd never replace?" },
  { id: "q119", theme: "simplicity", type: "you", text: "Tell us about a time less turned out to be more." },
  { id: "q120", theme: "simplicity", type: "scenario", text: "If I could only keep what fits in one bag..." },
  { id: "q121", theme: "simplicity", type: "scenario", text: "If I cleared my calendar for a month..." },
  { id: "q122", theme: "simplicity", type: "big", text: "Is a simple life a better life?" },
  { id: "q123", theme: "simplicity", type: "big", text: "Why do we make things more complicated than they need to be?" },
  // Kindness
  { id: "q124", theme: "kindness", type: "you", text: "Tell us about someone whose kindness you'll never forget." },
  { id: "q125", theme: "kindness", type: "you", text: "What's a small kindness that's easy to give?" },
  { id: "q126", theme: "kindness", type: "you", text: "Tell us about a time being kind was harder than it looked." },
  { id: "q127", theme: "kindness", type: "scenario", text: "If everyone did one kind thing a day..." },
  { id: "q128", theme: "kindness", type: "scenario", text: "If kindness were taught like maths..." },
  { id: "q129", theme: "kindness", type: "scenario", text: "Tell us about the kindest person you've never met." },
  { id: "q130", theme: "kindness", type: "big", text: "Is kindness a strength or a weakness?" },
  // Home
  { id: "q131", theme: "home", type: "you", text: "What makes a place feel like home to you?" },
  { id: "q132", theme: "home", type: "you", text: "Tell us about a home you've loved living in." },
  { id: "q133", theme: "home", type: "you", text: "What's the first thing you do when you get home?" },
  { id: "q134", theme: "home", type: "scenario", text: "If I could move my home anywhere..." },
  { id: "q135", theme: "home", type: "scenario", text: "Give us a tour of your favourite room." },
  { id: "q136", theme: "home", type: "big", text: "Is home a place or a feeling?" },
  { id: "q137", theme: "home", type: "big", text: "Can you have more than one home?" },
  // Resilience
  { id: "q138", theme: "resilience", type: "you", text: "Tell us about a setback that turned out to be useful." },
  { id: "q139", theme: "resilience", type: "you", text: "Tell us about someone who keeps going no matter what." },
  { id: "q140", theme: "resilience", type: "scenario", text: "If I could never fail at anything..." },
  { id: "q141", theme: "resilience", type: "scenario", text: "If I had one more try at something I gave up on..." },
  { id: "q142", theme: "resilience", type: "scenario", text: "Give us your advice for the day after a big mistake." },
  { id: "q143", theme: "resilience", type: "big", text: "Is resilience something you're born with or something you build?" },
  { id: "q144", theme: "resilience", type: "big", text: "Is it ever smarter to give up?" },
  // Friendship
  { id: "q145", theme: "friendship", type: "you", text: "How did you meet one of your closest friends?" },
  { id: "q146", theme: "friendship", type: "you", text: "Tell us about a friend who changed your life." },
  { id: "q147", theme: "friendship", type: "scenario", text: "Give us your advice for making friends as an adult." },
  { id: "q148", theme: "friendship", type: "big", text: "Can you be friends with someone completely different from you?" },
  { id: "q149", theme: "friendship", type: "big", text: "Do friendships need regular effort to survive?" },
  // Nature
  { id: "q150", theme: "nature", type: "you", text: "What's your favourite place to be outdoors?" },
  { id: "q151", theme: "nature", type: "you", text: "Tell us about a view that stopped you in your tracks." },
  { id: "q152", theme: "nature", type: "you", text: "What's something nature has taught you?" },
  { id: "q153", theme: "nature", type: "you", text: "Tell us about a time the weather changed your plans." },
  { id: "q154", theme: "nature", type: "scenario", text: "If I could spend a week anywhere in the wild..." },
  { id: "q155", theme: "nature", type: "big", text: "Do we need nature to be happy?" },
  { id: "q156", theme: "nature", type: "big", text: "Are we part of nature or separate from it?" },
  // Stories
  { id: "q157", theme: "stories", type: "you", text: "What's a story you never get tired of telling?" },
  { id: "q158", theme: "stories", type: "scenario", text: "If my life were a book, this chapter would be called..." },
  { id: "q159", theme: "stories", type: "scenario", text: "If I could live inside any story for a day..." },
  { id: "q160", theme: "stories", type: "scenario", text: "Tell us the story behind something you're wearing today." },
  { id: "q161", theme: "stories", type: "big", text: "Do the stories we tell about ourselves shape who we become?" },
  { id: "q162", theme: "stories", type: "big", text: "Is a true story always better than a made-up one?" },
  // Mentors
  { id: "q163", theme: "mentors", type: "you", text: "Who's someone who believed in you early on?" },
  { id: "q164", theme: "mentors", type: "you", text: "Tell us about the best teacher you've had, in or out of school." },
  { id: "q165", theme: "mentors", type: "you", text: "What's a lesson you learned from someone older than you?" },
  { id: "q166", theme: "mentors", type: "scenario", text: "If I could be mentored by anyone for a year..." },
  { id: "q167", theme: "mentors", type: "scenario", text: "If I could pass on one lesson to the next generation..." },
  { id: "q168", theme: "mentors", type: "scenario", text: "Give us the advice a great mentor gave you." },
  { id: "q169", theme: "mentors", type: "big", text: "Does everyone need a mentor?" },
  { id: "q170", theme: "mentors", type: "big", text: "Can you learn as much from a bad example as a good one?" },
  // Rest
  { id: "q171", theme: "rest", type: "you", text: "What does a proper day off look like for you?" },
  { id: "q172", theme: "rest", type: "you", text: "Tell us about the most relaxing place you've been." },
  { id: "q173", theme: "rest", type: "you", text: "What's something that helps you switch off?" },
  { id: "q174", theme: "rest", type: "you", text: "Tell us about a time you finally slowed down." },
  { id: "q175", theme: "rest", type: "scenario", text: "If everyone took a nap after lunch..." },
  { id: "q176", theme: "rest", type: "scenario", text: "Make the case for doing nothing this weekend." },
  { id: "q177", theme: "rest", type: "big", text: "Should we feel guilty for resting?" },
  { id: "q178", theme: "rest", type: "big", text: "Is rest productive?" },
  // Adventure
  { id: "q179", theme: "adventure", type: "you", text: "What's the most adventurous thing you've done?" },
  { id: "q180", theme: "adventure", type: "you", text: "Tell us about a trip that didn't go to plan." },
  { id: "q181", theme: "adventure", type: "you", text: "What's a place you'd love to explore?" },
  { id: "q182", theme: "adventure", type: "scenario", text: "If I could take off tomorrow with no plans..." },
  { id: "q183", theme: "adventure", type: "big", text: "Does adventure need to be far from home?" },
  { id: "q184", theme: "adventure", type: "big", text: "Is it better to travel with a plan or without one?" },
  // Being Present
  { id: "q185", theme: "being-present", type: "you", text: "When do you feel most in the moment?" },
  { id: "q186", theme: "being-present", type: "you", text: "Tell us about a moment you wish you could relive." },
  { id: "q187", theme: "being-present", type: "you", text: "What pulls you out of the present most often?" },
  { id: "q188", theme: "being-present", type: "you", text: "Tell us about a time you put your phone down and were glad you did." },
  { id: "q189", theme: "being-present", type: "scenario", text: "If I paid full attention for a whole day..." },
  { id: "q190", theme: "being-present", type: "scenario", text: "Walk us through the last five minutes, in detail." },
  { id: "q191", theme: "being-present", type: "big", text: "Is it possible to be fully present all the time?" },
  { id: "q192", theme: "being-present", type: "big", text: "Do we spend too much time thinking about the future?" },
  // Perspective
  { id: "q193", theme: "perspective", type: "you", text: "What's an opinion you've changed your mind about?" },
  { id: "q194", theme: "perspective", type: "you", text: "Tell us about a trip that changed how you see home." },
  { id: "q195", theme: "perspective", type: "you", text: "What's something that looks different to you now than it used to?" },
  { id: "q196", theme: "perspective", type: "scenario", text: "If I could see the world through someone else's eyes for a day..." },
  { id: "q197", theme: "perspective", type: "scenario", text: "If I could look at today from ten years in the future..." },
  { id: "q198", theme: "perspective", type: "scenario", text: "Explain something you love to someone who's never heard of it." },
  { id: "q199", theme: "perspective", type: "big", text: "Can two people be right about the same thing and still disagree?" },
  { id: "q200", theme: "perspective", type: "big", text: "Is it possible to see things as they really are?" },
  // Hope
  { id: "q201", theme: "hope", type: "you", text: "What's something you're looking forward to?" },
  { id: "q202", theme: "hope", type: "you", text: "What's a small thing that keeps you going on hard days?" },
  { id: "q203", theme: "hope", type: "scenario", text: "If I could guarantee one good thing for the world next year..." },
  { id: "q204", theme: "hope", type: "scenario", text: "If I could plant one idea in everyone's mind..." },
  { id: "q205", theme: "hope", type: "scenario", text: "Give us a reason to be hopeful today." },
  { id: "q206", theme: "hope", type: "big", text: "Is hope a feeling or a choice?" },
  { id: "q207", theme: "hope", type: "big", text: "Can you be hopeful and realistic at the same time?" },
  // Decisions
  { id: "q208", theme: "decisions", type: "you", text: "Tell us about a time you made a big call on the spot." },
  { id: "q209", theme: "decisions", type: "you", text: "What's a decision you always overthink?" },
  { id: "q210", theme: "decisions", type: "scenario", text: "If someone else made all my decisions for a week..." },
  { id: "q211", theme: "decisions", type: "scenario", text: "If I had to decide everything in five seconds..." },
  { id: "q212", theme: "decisions", type: "scenario", text: "Talk us through how you make a big decision." },
  { id: "q213", theme: "decisions", type: "big", text: "Are gut decisions better than careful ones?" },
  { id: "q214", theme: "decisions", type: "big", text: "Is having more options always a good thing?" },
  // Technology
  { id: "q215", theme: "technology", type: "you", text: "What's a piece of technology that changed your life?" },
  { id: "q216", theme: "technology", type: "you", text: "Tell us about an app you'd happily delete." },
  { id: "q217", theme: "technology", type: "you", text: "What's something you still do the old-fashioned way?" },
  { id: "q218", theme: "technology", type: "you", text: "Tell us about the first gadget you were excited to own." },
  { id: "q219", theme: "technology", type: "scenario", text: "If the internet went down for a month..." },
  { id: "q220", theme: "technology", type: "scenario", text: "If I could uninvent one thing..." },
  { id: "q221", theme: "technology", type: "scenario", text: "Explain your phone to someone from 1950." },
  { id: "q222", theme: "technology", type: "big", text: "Does technology make us more or less connected?" },
  // Honesty
  { id: "q223", theme: "honesty", type: "you", text: "Who's someone you can always count on for an honest opinion?" },
  { id: "q224", theme: "honesty", type: "you", text: "Tell us about a time honesty paid off." },
  { id: "q225", theme: "honesty", type: "you", text: "What's a piece of honest feedback that helped you?" },
  { id: "q226", theme: "honesty", type: "you", text: "Tell us about a truth you were nervous to share." },
  { id: "q227", theme: "honesty", type: "scenario", text: "If nobody could lie for a week..." },
  { id: "q228", theme: "honesty", type: "scenario", text: "Give us your advice for delivering bad news kindly." },
  { id: "q229", theme: "honesty", type: "big", text: "Is a white lie ever the right thing to do?" },
  { id: "q230", theme: "honesty", type: "big", text: "Is it possible to be too honest?" },
  // Philosophy
  { id: "q231", theme: "philosophy", type: "you", text: "What's a question you still don't have an answer to?" },
  { id: "q232", theme: "philosophy", type: "you", text: "What's a principle you try to live by?" },
  { id: "q233", theme: "philosophy", type: "you", text: "Tell us about a belief you've questioned." },
  { id: "q234", theme: "philosophy", type: "scenario", text: "If I could know the answer to one of life's big questions..." },
  { id: "q235", theme: "philosophy", type: "scenario", text: "Make the case that ordinary life is meaningful." },
  { id: "q236", theme: "philosophy", type: "big", text: "Do we have free will?" },
  { id: "q237", theme: "philosophy", type: "big", text: "Is it possible to be truly happy?" },
  // Music
  { id: "q238", theme: "music", type: "you", text: "What's a song that takes you straight back to a certain time?" },
  { id: "q239", theme: "music", type: "you", text: "Tell us about the best gig or concert you've been to." },
  { id: "q240", theme: "music", type: "you", text: "What's something you'd love to learn to play?" },
  { id: "q241", theme: "music", type: "you", text: "Tell us about the music you grew up with." },
  { id: "q242", theme: "music", type: "scenario", text: "If my life had a soundtrack..." },
  { id: "q243", theme: "music", type: "scenario", text: "If music disappeared for a year..." },
  { id: "q244", theme: "music", type: "scenario", text: "Convince us to listen to a genre we'd normally skip." },
  { id: "q245", theme: "music", type: "big", text: "Can music change how we feel about a place?" },
  { id: "q246", theme: "music", type: "big", text: "Is music better live or recorded?" },
  // Solitude
  { id: "q247", theme: "solitude", type: "you", text: "What's your favourite thing to do on your own?" },
  { id: "q248", theme: "solitude", type: "you", text: "Tell us about a place you go to be alone." },
  { id: "q249", theme: "solitude", type: "you", text: "What's something you've learned about yourself from time alone?" },
  { id: "q250", theme: "solitude", type: "scenario", text: "Make the case for a night in on your own." },
  { id: "q251", theme: "solitude", type: "big", text: "Is being alone the same as being lonely?" },
  { id: "q252", theme: "solitude", type: "big", text: "Do we get enough time alone?" },
  // AI
  { id: "q253", theme: "ai", type: "you", text: "What's something you've used AI for that genuinely helped?" },
  { id: "q254", theme: "ai", type: "you", text: "Tell us about a task you'd never hand over to AI." },
  { id: "q255", theme: "ai", type: "you", text: "What's something about AI that excites you?" },
  { id: "q256", theme: "ai", type: "scenario", text: "If AI did half my job tomorrow..." },
  { id: "q257", theme: "ai", type: "big", text: "Can AI ever be truly creative?" },
  { id: "q258", theme: "ai", type: "big", text: "Will AI make us smarter or lazier?" },
  // Work
  { id: "q259", theme: "work", type: "you", text: "What's the most interesting job you've had?" },
  { id: "q260", theme: "work", type: "you", text: "What's a part of your work that people don't see?" },
  { id: "q261", theme: "work", type: "you", text: "Tell us about a day at work you'll never forget." },
  { id: "q262", theme: "work", type: "scenario", text: "If I could swap jobs with anyone for a week..." },
  { id: "q263", theme: "work", type: "scenario", text: "If work had no meetings..." },
  { id: "q264", theme: "work", type: "scenario", text: "Explain your job in a way your grandparents would understand." },
  { id: "q265", theme: "work", type: "big", text: "Should work be a big part of who we are?" },
  { id: "q266", theme: "work", type: "big", text: "What makes work meaningful?" },
  // Growing Up
  { id: "q267", theme: "growing-up", type: "you", text: "What did you want to be when you grew up?" },
  { id: "q268", theme: "growing-up", type: "you", text: "Tell us about a moment you felt like an adult for the first time." },
  { id: "q269", theme: "growing-up", type: "you", text: "What's something from your childhood you'd bring back?" },
  { id: "q270", theme: "growing-up", type: "you", text: "Tell us about a lesson that took you a while to learn." },
  { id: "q271", theme: "growing-up", type: "scenario", text: "If I could spend one day as my younger self..." },
  { id: "q272", theme: "growing-up", type: "big", text: "Do we ever really finish growing up?" },
  { id: "q273", theme: "growing-up", type: "big", text: "Is growing up about gaining something or losing something?" },
  // Personal Development
  { id: "q274", theme: "personal-development", type: "you", text: "What's a strength someone pointed out that you hadn't noticed?" },
  { id: "q275", theme: "personal-development", type: "you", text: "Tell us about something you stopped doing that improved your life." },
  { id: "q276", theme: "personal-development", type: "you", text: "What's a book or podcast that actually changed how you do things?" },
  { id: "q277", theme: "personal-development", type: "you", text: "Tell us about a version of yourself you've outgrown." },
  { id: "q278", theme: "personal-development", type: "scenario", text: "If I could instantly gain one personal quality..." },
  { id: "q279", theme: "personal-development", type: "scenario", text: "If I wrote a self-help book, it would be called..." },
  { id: "q280", theme: "personal-development", type: "scenario", text: "Make the case that self-improvement can go too far." },
  { id: "q281", theme: "personal-development", type: "big", text: "Is it better to fix your weaknesses or build on your strengths?" },
  { id: "q282", theme: "personal-development", type: "big", text: "Can you change your personality?" }
];

/** Human-readable theme titles, keyed by theme slug. */
var PROMPT_THEMES = {
  "beginners-mind": "Beginner's Mind",
  "surprise": "Surprise",
  "ship-in-harbor": "A Ship in Harbor",
  "bring-your-own-sunshine": "Bring Your Own Sunshine",
  "navigating-transitions": "Navigating Transitions",
  "need-to-improve": "The Need to Improve",
  "laughter": "Laughter",
  "gratitude": "Gratitude",
  "heritage": "Heritage",
  "curiosity": "Curiosity",
  "listening": "Listening",
  "together": "Together",
  "small-steps": "Small Steps",
  "time": "Time",
  "creativity": "Creativity",
  "play": "Play",
  "simplicity": "Simplicity",
  "kindness": "Kindness",
  "home": "Home",
  "resilience": "Resilience",
  "friendship": "Friendship",
  "nature": "Nature",
  "stories": "Stories",
  "mentors": "Mentors",
  "rest": "Rest",
  "adventure": "Adventure",
  "being-present": "Being Present",
  "perspective": "Perspective",
  "hope": "Hope",
  "decisions": "Decisions",
  "technology": "Technology",
  "honesty": "Honesty",
  "philosophy": "Philosophy",
  "music": "Music",
  "solitude": "Solitude",
  "ai": "AI",
  "work": "Work",
  "growing-up": "Growing Up",
  "personal-development": "Personal Development"
};

/** Lookups. The app passes prompt text around as its currency; use these to
 *  get back to the prompt record (theme, type, id). */
var PROMPT_BY_TEXT = {};
var PROMPT_BY_ID = {};
PROMPTS.forEach(function (p) { PROMPT_BY_TEXT[p.text] = p; PROMPT_BY_ID[p.id] = p; });

/** Plain text list, kept for code that only needs the strings. */
var QUESTIONS = PROMPTS.map(function (p) { return p.text; });
