// Motivational lines for the Next Speaker reveal — warm, brief, confidence-boosting
var REVEAL_QUOTES = [
  "You're up! Take a breath — the room's with you.",
  "Take your time up here — there's no stopwatch on your thoughts.",
  "One honest idea beats a polished performance every time.",
  "They came to hear you, not a version of you.",
  "Speak like you're telling a friend — the room will lean in.",
  "You've got a perspective nobody else in this room has.",
  "A little nervous energy means you care. That's a good thing.",
  "Start anywhere. You'll find the thread as you go.",
  "You don't need the perfect opening — you need a real one.",
  "The room wants you to do well. Feel that.",
  "Say one thing you actually believe. That's enough to start.",
  "Your voice belongs here as much as anyone's.",
  "Take the pressure off — it's a conversation, not an exam.",
  "Slow down. Silence isn't empty — it gives people time to listen.",
  "You know more about this than you think you do.",
  "Trust the first sentence. The rest will follow.",
  "Nobody expects flawless. They expect genuine.",
  "Step up like you've done this before — because in a way, you have.",
  "Share one moment, one thought, one truth. That's a speech.",
  "The hardest part is walking up. You're already past it.",
  "Be curious out loud. That's what makes this interesting.",
  "You don't have to impress anyone — just connect.",
  "Pick one story. Tell it like you mean it.",
  "The room is on your side. Let them in.",
  "Speak from what you know. That's always enough.",
  "It's okay to pause. Pauses sound like confidence.",
  "Your take matters, even if it's still forming.",
  "Think of this as sharing, not performing.",
  "One clear thought is worth more than ten clever ones.",
  "You're not being judged — you're being listened to.",
  "Start small. A single sentence can open everything.",
  "Trust that people want to understand you.",
  "You belong in this moment. Take it.",
  "Say what you'd say if the room were full of friends.",
  "Don't rush to be brilliant. Rush to be real.",
  "You've prepared more than you realise — just by living.",
  "Let your personality show. That's the whole point.",
  "If you lose your place, breathe and begin again.",
  "Confidence isn't knowing it'll be perfect — it's showing up anyway.",
  "The best talks sound like someone thinking out loud.",
  "Give us one thing only you would say.",
  "You're allowed to be nervous and good at the same time.",
  "Make eye contact with one person. Then another. You're doing it.",
  "Simple words, said clearly, travel further than fancy ones.",
  "This is your minute — use it your way.",
  "Nobody knows your story like you do. Tell it.",
  "You don't need to fill every second. Let ideas land.",
  "Stand tall. The room already believes you can do this.",
  "Start with what feels true, not what sounds impressive.",
  "Every speaker before you felt this too. And they were fine.",
  "Your job is to be human up here. You're qualified.",
  "One breath, one sentence, one step at a time.",
  "The audience is rooting for a good moment. Help them find it.",
  "You have something worth hearing. Say it plainly.",
  "Forget perfect — aim for present.",
  "Talk to the room, not at it.",
  "You're not on trial. You're in conversation.",
  "Let yourself be a little imperfect. That's relatable.",
  "Trust the room to meet you halfway.",
  "Your opinion counts. Share it like it does.",
  "Speak as if you're glad to be here — because you are.",
  "You only need one good idea. You already have it.",
  "Take the space. You earned it by showing up.",
  "It's fine to smile. It helps everyone relax.",
  "Tell us what you noticed, felt, or learned. That's gold.",
  "You don't need a big finish — a honest ending is enough.",
  "The mic is yours. Use it gently.",
  "People remember how you made them feel, not every word.",
  "Be direct. Be kind. Be you.",
  "You're not here to prove anything — just to share.",
  "Let your enthusiasm show. It's contagious.",
  "One story from your life beats a hundred generalities.",
  "You're closer to ready than your nerves suggest.",
  "Speak like someone who has something to give.",
  "The room will follow you if you go at your own pace.",
  "Don't hide behind clever language. Say what you mean.",
  "You're allowed to enjoy this.",
  "Trust your instincts. They got you this far.",
  "Start talking — you'll figure out the rest on the way.",
  "This audience wants a person, not a presentation.",
  "Your voice is allowed to shake a little. Keep going.",
  "Make it feel like a gift, not a test.",
  "You have permission to take a moment before you begin.",
  "Say the thing you're slightly afraid to say. That's usually the good part.",
  "You're not competing with anyone up here.",
  "Let the question guide you — you don't need a script.",
  "Confidence grows as you speak. Start and let it catch up.",
  "Be generous with your thoughts. The room is listening.",
  "You don't need to know the ending when you start.",
  "Talk like you're explaining something you care about.",
  "The best version of you is the honest one.",
  "You're here because you belong here.",
  "One deep breath changes everything. Take it now.",
  "Keep it simple. Simple travels.",
  "Your experience is valid. Share it without apology.",
  "Imagine you're helping one person understand. That's enough.",
  "You can always pause, smile, and continue.",
  "Don't perform confidence — borrow it from the room for a minute.",
  "Say what you'd want to hear if you were in the audience.",
  "You're not empty. You have plenty to say.",
  "Let go of sounding smart. Aim for being clear.",
  "The room is warmer than you think.",
  "Your story doesn't need to be dramatic to matter.",
  "Trust that someone out there needs to hear this.",
  "You're doing something brave. Acknowledge that.",
  "Start with the easy part. Momentum builds.",
  "Nobody is waiting for you to fail.",
  "Speak from the chest, not the head.",
  "You get two minutes — that's plenty for one good thought.",
  "Be the speaker you'd want to listen to.",
  "Relax your shoulders. Unclench your jaw. Now begin.",
  "You're not behind. You're exactly on time.",
  "Give yourself credit for stepping up.",
  "The question is a friend. Let it lead you.",
  "You don't need to be funny, wise, and profound all at once.",
  "One genuine laugh or nod from the room is a win.",
  "Your pace is your pace. Own it.",
  "Think of this as practice for the person you're becoming.",
  "You're allowed to change your mind mid-sentence.",
  "The room can handle your honesty.",
  "Say less than you think you need to.",
  "You're not here to entertain — you're here to connect.",
  "Trust the silence after a good point. Let it sit.",
  "Your nervousness is invisible to most of the room.",
  "Bring one detail. Details make things real.",
  "You already have everyone's attention. Use it well.",
  "Don't aim for applause — aim for a moment of truth.",
  "You're more ready than you feel.",
  "Speak like you're opening a door, not building a wall.",
  "The floor is yours. Take your time crossing it.",
  "One honest answer is braver than a safe one.",
  "You're not alone up there — the whole room is with you.",
  "Let your natural tone come through.",
  "You don't need to rush to the point. Enjoy getting there.",
  "Every good speaker started exactly where you are.",
  "Share something small and specific. It'll land.",
  "You're allowed to be yourself — that's the brief.",
  "Think conversation, not monologue.",
  "Your perspective is the reason you're up here.",
  "Breathe in. Speak out. Repeat as needed.",
  "The room trusts you to be real.",
  "You won't get everything right. You will get enough right.",
  "Start before you feel ready. That's how ready happens.",
  "Give the room one thing to remember.",
  "You're not too quiet, too loud, or too anything — you're you.",
  "Let the words come. Don't force them.",
  "This is a safe room. Treat it that way.",
  "Your turn is a chance, not a burden.",
  "Say what matters to you and stop when you're done.",
  "Confidence is just showing up and continuing.",
  "You're here to add something, not to prove something.",
  "Trust that your voice carries further than you think.",
  "One clear example beats ten vague statements.",
  "You're doing fine already — you walked up here.",
  "Don't overthink the first line. Any line works.",
  "The audience is curious about you. Satisfy that curiosity.",
  "You're allowed to take up space.",
  "Speak with the same warmth you'd use at a dinner table.",
  "Your answer doesn't need to be complete — it needs to be yours.",
  "Let yourself be surprised by what you say.",
  "You're not reciting — you're responding.",
  "The room will forgive a stumble. They won't forget honesty.",
  "Keep your eyes up. You're talking to people, not the floor.",
  "You have two minutes and a room full of allies.",
  "Start where the energy is — usually that's what you care about most.",
  "You're not here to be perfect. You're here to be present.",
  "One breath of courage is all this takes.",
  "Trust the room. They're glad it's you.",
  "Say it like you mean it — because you do.",
  "You're already doing the hard part. The rest is just talking.",
  "Bring your whole self, not your polished self.",
  "The question asked for you specifically. Answer as you.",
  "You don't need permission to have an opinion. You have the mic.",
  "Slow is smooth. Smooth is good.",
  "You're not being graded on eloquence — you're being heard.",
  "Let this be easy. It can be easy.",
  "Your story is enough. Tell it simply.",
  "The room is ready when you are.",
  "One thought, spoken clearly, is a complete answer.",
  "You're not on stage alone — everyone here wants this to go well.",
  "Trust that you have something to say. You always do.",
  "Begin with what feels most true right now.",
  "You're allowed to enjoy your own answer.",
  "Speak as if the person in the back row matters — they do.",
  "Don't chase perfection. Chase connection.",
  "You're up — and you're going to be great.",
  "Take a breath, trust yourself, and begin.",
  "The room is yours for the next few minutes. Make them count.",
  "You've got this. Now show us what you've got.",
  "Walk up like someone who's allowed to be here — because you are.",
  "Your first sentence doesn't have to be your best. It just has to be first.",
  "The room would rather hear you stumble than stay silent.",
  "Give yourself ten seconds to settle. Then start.",
  "You're not filling time — you're offering something.",
  "Let your answer be a little messy. Real things usually are.",
  "Nobody in this room needs you to be anyone but you.",
  "Hold the pause after something good. You earned it.",
  "You're about to do something most people avoid. That counts.",
  "Trust the question. Trust yourself. Begin.",
  "You're not here to win the room — you're here to reach it."
];

function pickRevealQuote(usedSet) {
  var available = REVEAL_QUOTES.filter(function (q) { return !usedSet.has(q); });
  var pool = available.length > 0 ? available : REVEAL_QUOTES;
  return pool[Math.floor(Math.random() * pool.length)];
}
